name: libplctag4j CI

on:
  push:
    branches: [ release, prerelease ]
  pull_request:
    branches: [ release, prerelease ]

jobs:

  build:
    name: Generate JAR
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build Release JAR
      run: gradle clean jar
              
    - name: Test Release JAR
      run: gradle test --stacktrace
              
    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: JAR
        path: ${{ github.workspace }}/app/build/libs/libplctag4j-*.jar