name: libplctag4j CI

on:
  push:
    branches: [ release, prerelease ]
  pull_request:
    branches: [ release, prerelease ]

jobs:

  build:
    name: Generate JAR
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build Release JAR
      run: gradle clean jar
              
    - name: Test Release JAR
      run: gradle test --stacktrace --info

    - name: Get artifact name
      run: |
        export ARTIFACT_NAME=`ls ${{ github.workspace }}/build/libs/libplctag4j-*.jar | tail -1 | basename`
        echo "ARTIFACT_NAME=${ARTIFACT_NAME}"
        echo "::set-env name=ARTIFACT_NAME::${ARTIFACT_NAME}"
              
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ github.workspace }}/build/libs/libplctag4j-*.jar