name: libplctag4j CI

on:
  push:
    branches: [ release, prerelease ]
  pull_request:
    branches: [ release, prerelease ]

jobs:

  ubuntu-test:
    name: Ubuntu Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build Release JAR
      run: gradle -b build-jar.gradle clean shadowJar

    - name: Test Release JAR
      run: gradle -b build-jar.gradle test --stacktrace --info

  macos-test:
    name: macOS Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build Release JAR
      run: gradle -b build-jar.gradle clean shadowJar

    - name: Test Release JAR
      run: gradle -b build-jar.gradle test --stacktrace --info

  windows-test:
    name: Windows Test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build Release JAR
      run: gradle -b build-jar.gradle clean shadowJar

    - name: Test Release JAR
      run: gradle -b build-jar.gradle test --stacktrace --info

  generate-artifacts:
    needs: [ ubuntu-test, windows-test, macos-test ]
    name: Generate artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build Release JAR
      run: gradle -b build-jar.gradle clean shadowJar

    - name: Build POM file
      run: gradle -b build-jar.gradle publishToMavenLocal

    - name: Build Javadoc
      run: gradle -b build-jar.gradle javadoc

    - name: Get artifact name
      run: |
        ls ${{ github.workspace }}/build/libs/libplctag4j*
        export FULL_NAME=`ls ${{ github.workspace }}/build/libs/libplctag4j-*.jar | tail -n 1`
        echo "FULL_NAME=${FULL_NAME}"
        echo "::set-env name=FULL_NAME::${FULL_NAME}"
        export ARTIFACT_NAME=`basename -s .jar ${FULL_NAME}`
        echo "ARTIFACT_NAME=${ARTIFACT_NAME}"
        echo "::set-env name=ARTIFACT_NAME::${ARTIFACT_NAME}"
        PARTS=($(echo "$ARTIFACT_NAME" | tr '-' "\n"))
        export VERSION="${PARTS[1]}-${PARTS[2]}"
        echo "VERSION=${VERSION}"
        echo "::set-env name=VERSION::${VERSION}"
        export POM_NAME=`ls ${{ github.workspace }}/build/publications/mavenJava/pom-default.xml | tail -n 1`
        echo "POM_NAME=${POM_NAME}"
        echo "::set-env name=POM_NAME::${POM_NAME}"

    - name: Upload full JAR to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.FULL_NAME }}

    - name: Upload docs to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ github.workspace }}/build/docs

    - name: Upload full JAR to Bintray
      run: |
        ls ${{ github.workspace }}/build/libs
        if [ -e ${{ env.FULL_NAME }} ]; then
          echo "Uploading full JAR file."
          echo "curl -T ${{ env.FULL_NAME }} -ukyle-github:${{secrets.BINTRAY_API_KEY}} https://api.bintray.com/content/libplctag/libplctag4j/io.github.libplctag/${{ env.VERSION }}/${{ env.ARTIFACT_NAME }}.jar?publish=1&override=1"
          curl -T ${{ env.FULL_NAME }} -ukyle-github:${{secrets.BINTRAY_API_KEY}} https://api.bintray.com/content/libplctag/libplctag4j/io.github.libplctag/${{ env.VERSION }}/${{ env.ARTIFACT_NAME }}.jar?publish=1&override=1
        else
          echo "Full JAR file not found!"
        fi

    - name: Upload POM to Bintray
      run: |
        ls ${{ github.workspace }}/build/publications/mavenJava/
        if [ -e "${{ env.POM_NAME }}" ]; then
          echo "Uploading POM file."
          echo "curl -T ${{ env.POM_NAME }} -ukyle-github:${{secrets.BINTRAY_API_KEY}} https://api.bintray.com/content/libplctag/libplctag4j/io.github.libplctag/${{ env.VERSION }}/pom.xml?publish=1&override=1"
          curl -T ${{ env.POM_NAME }} -ukyle-github:${{secrets.BINTRAY_API_KEY}} https://api.bintray.com/content/libplctag/libplctag4j/io.github.libplctag/${{ env.VERSION }}/pom.xml?publish=1&override=1
        else
          echo "POM file found!"
        fi
