name: libplctag4j CI

on:
  push:
    branches: [ release, prerelease, android-jar ]
  pull_request:
    branches: [ release, prerelease, android-jar ]

jobs:

  ubuntu:
    name: Generate artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build Release JAR
      run: gradle clean libplctag4j-jar:jar

    - name: Test Release JAR
      run: gradle libplctag4j-jar:test --stacktrace --info

    - name: Build Javadoc
      run: gradle libplctag4j-jar:javadoc

    - name: Get artifact name
      run: |
        export FULL_NAME=`ls ${{ github.workspace }}/libplctag4j-jar/build/libs/libplctag4j-*.jar | tail -n 1`
        echo "FULL_NAME=${FULL_NAME}"
        echo "::set-env name=FULL_NAME::${FULL_NAME}"
        export ARTIFACT_NAME=`basename -s .jar ${FULL_NAME}`
        echo "ARTIFACT_NAME=${ARTIFACT_NAME}"
        echo "::set-env name=ARTIFACT_NAME::${ARTIFACT_NAME}"

    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.FULL_NAME }}

    - name: Upload docs
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ github.workspace }}/build/docs

  macos-test:
    name: macOS Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build Release JAR
      run: gradle clean jar

    - name: Test Release JAR
      run: gradle test --stacktrace --info

  windows-test:
    name: Windows Test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build Release JAR
      run: gradle clean jar

    - name: Test Release JAR
      run: gradle test --stacktrace --info

